### ISSUE TITLE
Refactor terraform layout to support scalable management of AWS accounts

### ISSUE THREAD

**Issue by amitfreeman-gov** [18F/aws-admin#116]
## Background information

In order to be able to globally manage AWS accounts, allowing for independent use cases to be implemented in a modular format, lay out terraform in a way that makes it simple to add and remove items at scale

## Acceptance criteria

- [x] Remote state enabled, with locking
- [ ] Modularized layout with components covering different use cases
- [ ] Documentation for adding/removing new accounts

**Comment by afeld** [comment]
Closing this out as "not actionable" — we can refactor as we find opportunities going forward.

**Comment by afeld** [comment]
@amitfreeman-gov to write up what he had in mind here and then close out.

**Comment by afeld** [comment]
> Modularized layout with components covering different use cases

With configuration we already have, or do you mean making modules preemptively for future configuration?

> Documentation for adding…new accounts

Beyond what's in [the issue template](https://github.com/18F/aws-admin/blob/master/.github/ISSUE_TEMPLATE/new_account.md), you mean?

**Comment by afeld** [comment]
Closing as stale.
