### ISSUE TITLE
Resolve critical root user findings from Security hub for forms.gov accounts - due 5/28

### ISSUE THREAD

**Issue by rcoxGSA** [18F/aws-admin#141]
## Background Information
There are two critical findings from security hub related to the root user that need resolved for the three forms.gov accounts:

- tts-faas-dev
- tts-faas-test
- tts-faas-prod

The two findings that need resolved are:
- IAM.4 IAM root user access key should not exist
- 1.12 Ensure no root account access key exists

## Acceptance Criteria

- [x] @rcoxGSA confirms Security Hub findings no longer exist

**Comment by JJediny** [comment]
@rcoxGSA please confirm 
<img width="1228" alt="Screen Shot 2021-05-27 at 1 47 16 PM" src="https://user-images.githubusercontent.com/6350035/119873469-940a5400-bef2-11eb-9632-1c428a5b77e0.png">
<img width="1203" alt="Screen Shot 2021-05-27 at 1 48 56 PM" src="https://user-images.githubusercontent.com/6350035/119873470-940a5400-bef2-11eb-8016-495f0500f881.png">
<img width="1218" alt="Screen Shot 2021-05-27 at 1 50 14 PM" src="https://user-images.githubusercontent.com/6350035/119873472-940a5400-bef2-11eb-87bf-fbb39b438272.png">

**Comment by rcoxGSA** [comment]
confirmed! thanks @JJediny
