### ISSUE TITLE
experiment with Cloud Custodian

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#17]
https://cloudcustodian.io/

@JJediny I feel like I remember you having some example configuration somewhere—that ring a bell?

**Comment by JJediny** [comment]
@afeld I'm going to triage and move the current aws related issues in https://github.com/18f/tts-tech-portfolio/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+aws

**Comment by its-a-lisa** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/195
