### ISSUE TITLE
As the Tech Portfolio, I want to ensure AWS users use MFA

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#22]
https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_users-self-manage-mfa-and-creds.html

Not necessary if we start doing single sign-on (SSO) using something else that enforces it. cc 18F/tts-tech-portfolio#19

**Comment by JJediny** [comment]
Closing in favor of the epic https://github.com/18F/tts-tech-portfolio/issues/204
