### ISSUE TITLE
audit IAM policies that aren't being used

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#23]
## User Story:

As someone responsible for AWS Admin, I would like to audit IAM permissions

## Problem Statement: 

Wondering if there's something we can do centrally to be safer about this by default. 

## Background information: 

[Login.gov discussion that spurred this.](https://docs.google.com/document/d/1a6N8DxnThYsgEay6CkeW_J0-MiphXhghUYjMQhpTAwU/edit#heading=h.iz5wwlbhsruc) 

## Actions to take:  

- [x] Review Your AWS Account Credentials
- [x] Review Your IAM Users
- [x] Review Your IAM Groups
- [x] Review Your IAM Roles
- [x] Review Your IAM Providers for SAML and OpenID Connect (OIDC)
- [ ] Review Your Mobile Apps
- [ ] Review Your Amazon EC2 Security Configuration
- [x] Review AWS Policies in Other Services
- [ ] Monitor Activity in Your AWS Account

## Acceptance criteria: 

- [ ] We have notified respective teams about unused policies
- [ ] We have a documented way to perform this audit in the future
- [x] Create new issue around doing so on an ongoing/automated/real-time basis

## Supporting Documentation:

Some tools that came up:
- [repokid](https://github.com/Netflix/repokid)
- [CloudMapper](https://github.com/duo-labs/cloudmapper)
- [CloudTracker](https://github.com/duo-labs/cloudtracker)
- [AWS Access Advisor](https://aws.amazon.com/blogs/security/automate-analyzing-permissions-using-iam-access-advisor/)

**Comment by afeld** [comment]
cc https://github.com/18F/aws-admin/issues/20

**Comment by JJediny** [comment]
evalutate https://github.com/bridgecrewio/AirIAM

**Comment by afeld** [comment]
- [ ] @amitfreeman-gov revise Acceptance Criteria

**Comment by amitfreeman-gov** [comment]
[unused_policies.txt](https://github.com/18F/aws-admin/files/5617350/unused_policies.txt)
Attached list of policies not being used based on the airiam report
