### ISSUE TITLE
de-fork

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#3]
This repository isn't really meant to be a fork of the Open Source Policy, so let's get it disconnected as such. I have heard GitHub support can change that on an existing repo, so just reach out to them.

**Comment by JJediny** [comment]
only did this to leverage as a template; so not to recreate licence etc

**Comment by afeld** [comment]
Ohhhhh interesting. You're right, I totally assumed it said "forked from" rather than "generated from". My mistake, sorry!
