### ISSUE TITLE
Single IAM user per person across accounts

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#39]
## Background information

> AWS Single Sign-On (SSO) makes it easy to centrally manage access to multiple AWS accounts…and provide users with single sign-on access to all their assigned accounts…from one place. With AWS SSO, you can easily manage SSO access and user permissions to all of your accounts in AWS Organizations centrally. SSO configures and maintains all the necessary permissions for your accounts automatically, without requiring any additional setup in the individual accounts.

https://aws.amazon.com/single-sign-on/

## User stories

- As someone who manages TTS AWS accounts, I want a single place to offboard people from AWS.
- As a TTS AWS user, I only want to have a single set of AWS credentials to deal with.

## Acceptance criteria

- Every TTS AWS user only has a single set of IAM credentials

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Would like to see some implementation steps of this card before giving 👍 -- think this could benefit from being broken down into smaller tasks.

**Comment by afeld** [comment]
Perhaps we narrow this to "create a plan for…"?

**Comment by afeld** [comment]
Let's scope to commercial (not GovCloud) accounts.

**Comment by its-a-lisa-at-work** [comment]
@JJediny can we put a `Due Date` on this since we moved it back into the backlog after it was `Sprint Planned` ... something within the next 4 weeks/2 sprints

**Comment by afeld** [comment]
We can also scope to exclude cloud.gov/login.gov if that simplifies things.

**Comment by JJediny** [comment]
User Cleanup Crosswalk sheet https://docs.google.com/spreadsheets/d/18IQviPnMUKPmb0JqAJDBcBuBOtJJAKKC2GfUIQXXw3g/edit?usp=sharing

**Comment by afeld** [comment]
Created follow-up issues.
