### ISSUE TITLE
Finish setting up account billling threshold alerting

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/aws-admin#44]
## Background information

Broken out from https://github.com/18F/aws-admin/issues/40. Follow-up to https://github.com/18F/aws-admin/issues/19.

## Acceptance criteria

- Account billing threshold billing is 100% complete

**Comment by its-a-lisa-at-work** [comment]
@JJediny assigning to you since I probably won't be able to get to this any time soon

**Comment by afeld** [comment]
Oh, forgot we made a new issue for this! Completed in https://github.com/18F/aws-admin/pull/51.
