### ISSUE TITLE
Properly segment programs and their AWS accounts

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/aws-admin#46]
## Background information

Broken out from https://github.com/18F/aws-admin/issues/40

## Acceptance criteria

- Programs are properly segmented

**Comment by afeld** [comment]
Can you elaborate on what "segmented" means in this case?

**Comment by JJediny** [comment]
Based on current usage there is proper segmentation at the account level outside of sandbox accounts. Not planning to address this in the short term
