### ISSUE TITLE
Four more accounts for cloud.gov, 2 in each AWS partition

### ISSUE THREAD

**Issue by pburkholder** [18F/aws-admin#49]
In addition to the account we already have for cloud.gov, we would like the following. 

* E/W
  * ~master~ primary (from which we'll use AssumeRole to do work in the subsidiary accounts)
  * sandbox (for developer learning/testing/experimentation)
* GovCloud
  * ~master~ primary (from which we'll use AssumeRole to do work in the subsidiary accounts)
  * sandbox (for developer learning/testing/experimentation)

Is that something you can help with?

**Comment by pburkholder** [comment]
Any status on this one?

**Comment by pburkholder** [comment]
Is this do-able in the next few weeks? It's a pre-requisite to addressing some of the core issues behind the Jan 2018 cloud.gov outage https://cloudgov.statuspage.io/incidents/32bd83xh70qk

**Comment by pburkholder** [comment]
I fell into old naming habits. The top level accounts should be 'main' or 'primary' not 'master'

**Comment by afeld** [comment]
AWS ran into an unexpected issue sending the GovCloud credentials; waiting on them to investigate.

**Comment by afeld** [comment]
## Who/what the account is for?

cloud.gov jump and sandbox

## Do you need an associated GovCloud account?

Yes, for both

## Checklist for admins

### jump

1. [x] [Confirm they are paying into the existing contract](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=1269506691)
1. [x] Create an account using the [`account`](https://github.com/18F/aws-admin/tree/master/terraform/account) module
1. [x] Set up root user
   1. [x] [Sign in as the root user](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html#orgs_manage_accounts_access-as-root)
   1. [ ] [Change account email](https://console.aws.amazon.com/billing/home#/account) to `devops+aws-<account number>@gsa.gov`
   1. [ ] [Set up MFA](https://console.aws.amazon.com/iam/home?#/security_credentials)
   1. [ ] [Add to KeePass](https://drive.google.com/drive/folders/1iQnvC8o_MU_DR5u7TYtC9pEKZXtBq03f?usp=sharing) and re-upload database
1. [ ] Set the [program team mailing list](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795) as the [Operations Contact](https://console.aws.amazon.com/billing/home?#/account)
1. [ ] Add to [account spreadsheet](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [ ] If GovCloud is needed, send a request with the account number to govcloud-onboarding@amazon.com and CC cloudteam@4points.com, devops@gsa.gov, and brian.burns@gsa.gov
1. [ ] Set up cross-account access
   1. [ ] [Create a role for "another AWS account"](https://console.aws.amazon.com/iam/home#/roles$new?step=type&roleType=crossAccount). For the `Account ID`, enter `133032889584`.
   1. [ ] Select the [`AdministratorAccess`](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html#jf_administrator) policy.
   1. [ ] Add a tag of `Project`: `https://github.com/18F/aws-admin`.
   1. [ ] Set a `Role name` of `CrossAccountAdmin`.
   1. [ ] Create it.
   1. [ ] Mark a `Y` in the `Role switching enabled?` column of [the AWS accounts list](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [ ] Set up budgeting
   1. [ ] Sign into payer account
   1. [ ] Add to [Cost Category](https://console.aws.amazon.com/billing/home#/costcategories)
1. [ ] Set up IAM
   1. [ ] [Create a group](https://console.aws.amazon.com/iam/home#/groups) called `Administrators`
   1. [ ] Attach the `AdministratorAccess` policy to that group
   1. [ ] Create an IAM user in the `Administrators` group for the requester
   1. [ ] Send them the temporary password via Google Hangouts

### sandbox

1. [x] [Confirm they are paying into the existing contract](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=1269506691)
1. [x] Create an account using the [`account`](https://github.com/18F/aws-admin/tree/master/terraform/account) module
1. [x] Set up root user
   1. [x] [Sign in as the root user](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html#orgs_manage_accounts_access-as-root)
   1. [ ] [Change account email](https://console.aws.amazon.com/billing/home#/account) to `devops+aws-<account number>@gsa.gov`
   1. [ ] [Set up MFA](https://console.aws.amazon.com/iam/home?#/security_credentials)
   1. [ ] [Add to KeePass](https://drive.google.com/drive/folders/1iQnvC8o_MU_DR5u7TYtC9pEKZXtBq03f?usp=sharing) and re-upload database
1. [ ] Set the [program team mailing list](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795) as the [Operations Contact](https://console.aws.amazon.com/billing/home?#/account)
1. [ ] Add to [account spreadsheet](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [ ] If GovCloud is needed, send a request with the account number to govcloud-onboarding@amazon.com and CC cloudteam@4points.com, devops@gsa.gov, and brian.burns@gsa.gov
1. [ ] Set up cross-account access
   1. [ ] [Create a role for "another AWS account"](https://console.aws.amazon.com/iam/home#/roles$new?step=type&roleType=crossAccount). For the `Account ID`, enter `133032889584`.
   1. [ ] Select the [`AdministratorAccess`](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html#jf_administrator) policy.
   1. [ ] Add a tag of `Project`: `https://github.com/18F/aws-admin`.
   1. [ ] Set a `Role name` of `CrossAccountAdmin`.
   1. [ ] Create it.
   1. [ ] Mark a `Y` in the `Role switching enabled?` column of [the AWS accounts list](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [ ] Set up budgeting
   1. [ ] Sign into payer account
   1. [ ] Add to [Cost Category](https://console.aws.amazon.com/billing/home#/costcategories)
1. [ ] Set up IAM
   1. [ ] [Create a group](https://console.aws.amazon.com/iam/home#/groups) called `Administrators`
   1. [ ] Attach the `AdministratorAccess` policy to that group
   1. [ ] Create an IAM user in the `Administrators` group for the requester
   1. [ ] Send them the temporary password via Google Hangouts

**Comment by afeld** [comment]
Emailed support to get GovCloud credentials rotated, as directed. Waiting to hear back.

**Comment by afeld** [comment]
Signed and sent the Account Access Certification back to AWS. Waiting again.

**Comment by afeld** [comment]
More back-and-forths; the saga continues.

**Comment by afeld** [comment]
- [ ] sandbox GovCloud account
    - [x] Send account recovery certification
    - [x] Receive credential retrieval instructions
    - [x] Successfully retrieve credentials
    - [x] Add (provided) GovCloud root account access key and secret to KeePass and re-upload database
    - [ ] Create user for @pburkholder and send credentials
- [ ] jump GovCloud account
    - [x] Send account recovery certification
    - [ ] Receive credential retrieval instructions
    - [ ] Successfully retrieve credentials
    - [ ] Add (provided) GovCloud root account access key and secret to KeePass and re-upload database
    - [ ] Create user for @pburkholder and send credentials

**Comment by afeld** [comment]
Phew, finally complete.
