### ISSUE TITLE
As a TTS + GSA IT stakeholder, I'm curious about the roadmap

### ISSUE THREAD

**Issue by cantsin** [18F/aws-admin#6]
It would be nice to have a roadmap for this AWS authentication centralization project to share with all relevant stakeholders, including work expected in the current scope of 80 hours and possible additions in the future.

**Comment by cantsin** [comment]
We will not be able to do AWS authentication centralization due to inherent limits with Cognito, but will share recommendations on next steps in https://docs.google.com/document/d/1qhulMoqbkpZuT_wasosJQkcBgrnwntLuz2SYJWzcklw/edit?usp=sharing (note: access may be restricted)

**Comment by cantsin** [comment]
[AWS and login.gov writeup](https://docs.google.com/document/d/1nO0UIbi3DCkSVDUTLblKIEPmnJJt8Vt-A00w4QSYTmQ/edit?usp=sharing) -- please note, access may be restricted.

**Comment by JJediny** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/70
