### ISSUE TITLE
create Federalist sandbox

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#62]
## Who/what the account is for?

A sandbox environment for Federalist, requested by @davemcorwin.

## Do you need an associated GovCloud account?

No.

## Checklist for admins

1. [x] [Confirm they are paying into the existing contract](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=1269506691)
1. [x] Create an account using the [`account`](https://github.com/18F/aws-admin/tree/master/terraform/account) module
1. [x] Set up root user
   1. [x] [Sign in as the root user](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html#orgs_manage_accounts_access-as-root)
   1. [x] [Change account email](https://console.aws.amazon.com/billing/home#/account) to `devops+aws-<account number>@gsa.gov`
   1. [x] [Set up MFA](https://console.aws.amazon.com/iam/home?#/security_credentials)
   1. [x] [Add to KeePass](https://drive.google.com/drive/folders/1iQnvC8o_MU_DR5u7TYtC9pEKZXtBq03f?usp=sharing) and re-upload database
1. [x] Set the [program team mailing list](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795) as the [Operations Contact](https://console.aws.amazon.com/billing/home?#/account)
1. [x] Add to [account spreadsheet](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [x] Set up cross-account access
   1. [x] [Create a role for "another AWS account"](https://console.aws.amazon.com/iam/home#/roles$new?step=type&roleType=crossAccount). For the `Account ID`, enter `133032889584`.
   1. [x] Select the [`AdministratorAccess`](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html#jf_administrator) policy.
   1. [x] Add a tag of `Project`: `https://github.com/18F/aws-admin`.
   1. [x] Set a `Role name` of `CrossAccountAdmin`.
   1. [x] Create it.
   1. [x] Mark a `Y` in the `Role switching enabled?` column of [the AWS accounts list](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [x] Set up budgeting
   1. [x] Sign into payer account
   1. [x] Add to [Cost Category](https://console.aws.amazon.com/billing/home#/costcategories)
1. [x] Set up IAM
   1. [x] [Create a group](https://console.aws.amazon.com/iam/home#/groups) called `Administrators`
   1. [x] Attach the `AdministratorAccess` policy to that group
   1. [x] Create an IAM user in the `Administrators` group for the requester
   1. [x] Send them the temporary password via Google Hangouts

**Comment by its-a-lisa-at-work** [comment]
for the first step of checking if they are paying into the current contract; I am unsure since cloud.gov is but there isn't a separate line item for federalist -- my judgement says that they are; but if someone else wants to provide any other differing opinion, let me know. Until then, I am going to mark it as complete and go on to the next step.
