### ISSUE TITLE
sandbox account for wouhib.worku@gsa.gov

### ISSUE THREAD

**Issue by wouhibworku** [18F/aws-admin#67]
I recently joined the Infrastracture CoE team and i am requesting a sandbox account for prototyping, running experiments, etc...

**Comment by saz33m** [comment]
@wouhibworku We have a CoE AWS and Azure sandbox environment. Please fill out this form and I can provision you. https://docs.google.com/forms/d/1MrhLWxci95J3chE8CFTJ7tPeT_Y-xDbMk_8YYawr5zk/edit#responses
