### ISSUE TITLE
Three (3) AWS GovCloud accounts for Forms as a Service

### ISSUE THREAD

**Issue by saz33m** [18F/aws-admin#68]
## Who/what the account is for?

Forms as a Service. We need DEV, TEST and PROD.

## Do you need an associated GovCloud account?

Yes, each account should be established in GovCloud region.

## Checklist for admins

1. [x] [Confirm they are paying into the existing contract](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=1269506691)
1. [x] Create an account using the [`account`](https://github.com/18F/aws-admin/tree/master/terraform/account) module 
   - [x] [pull request](https://github.com/18F/aws-admin/pull/73)
1. [x] Add to [account spreadsheet](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [x] Set up root user
   1. [x] [Sign in as the root user](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html#orgs_manage_accounts_access-as-root)
   1. [x] [Set up MFA](https://console.aws.amazon.com/iam/home?#/security_credentials)
   1. [x] [Add to KeePass](https://drive.google.com/drive/folders/1iQnvC8o_MU_DR5u7TYtC9pEKZXtBq03f?usp=sharing) and re-upload database
1. [x] Set the [program team mailing list](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795) as the [Operations Contact](https://console.aws.amazon.com/billing/home?#/account)
1. [x] Set up GovCloud (if applicable)
   1. [x] Send a request with the account number to govcloud-onboarding@amazon.com and CC cloudteam@4points.com, devops@gsa.gov, and brian.burns@gsa.gov
   1. [x] Get credentials from AWS
   1. [x] Create user for requester
1. [x] Set up cross-account access
   1. [x] [Create a role for "another AWS account"](https://console.aws.amazon.com/iam/home#/roles$new?step=type&roleType=crossAccount). For the `Account ID`, enter `133032889584`.
   1. [x] Select the [`AdministratorAccess`](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html#jf_administrator) policy.
   1. [x] Add a tag of `Project`: `https://github.com/18F/aws-admin`.
   1. [x] Set a `Role name` of `CrossAccountAdmin`.
   1. [x] Create it.
   1. [x] Mark a `Y` in the `Role switching enabled?` column of [the AWS accounts list](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
1. [x] Set up budgeting
   1. [x] Sign into payer account
   1. [x] Add to [Cost Category](https://console.aws.amazon.com/billing/home#/costcategories)
      - Note you may need to use the JSON editor, as the account doesn't show up in the selection box right away
1. [x] Set up IAM
   1. [x] Configure the account using the [`account_setup`](https://github.com/18F/aws-admin/tree/master/terraform/account_setup) module
   1. [x] Sign into the new account using the [`Switch role URL`](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0)
   1. [x] [Create an IAM user](https://console.aws.amazon.com/iam/home#/users$new?step=details) in the `Administrators` group for the requester
   1. [x] Send them the temporary password via Google Hangouts
   1. [x] Have the requester confirm they set up MFA

**Comment by saz33m** [comment]
requested naming convention
 `tts-faas-dev`
 `tts-faas-test`
 `tts-faas-prod`

**Comment by afeld** [comment]
Are you sure you need GovCloud? It greatly constrains the services you can use, adds management overhead, etc.

**Comment by saz33m** [comment]
Yes, absolutely certain. This conclusion was reached per 18F Engineering recommendation and discussions w/ GSA IT security staff.

**Comment by its-a-lisa-at-work** [comment]
marking this as `g:accepted` since it is a checklist type of task

**Comment by saz33m** [comment]
@its-a-lisa-at-work Will this issue be part of your new sprint? :) Thanks

**Comment by its-a-lisa-at-work** [comment]
@saz33m yup! working on it now :)

**Comment by rcoxGSA** [comment]
@its-a-lisa-at-work could we setup a meeting to go over the governance process and other things like requesting additional accounts for our team?

**Comment by saz33m** [comment]
@rcoxGSA Once @its-a-lisa-at-work has provisioned our AWS accounts, we will have the ability to fully self-manage. Remember, it's AWS account level access that we are getting (not just IAM users).

**Comment by rcoxGSA** [comment]
Great! We should talk through how we're setting up these additional accounts, who has access to create the accounts,  and establishing thresholds so that we don't go through the budget too quickly.

**Comment by JJediny** [comment]
completed as much as we can email sent to convert accounts into govcloud once done will follow up to add to budget and close
