### ISSUE TITLE
clean up AWS account spreadsheet

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#69]
## Background information

There are a bunch of sheets that don't seem to be used anymore.

https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0

## User stories

- As someone who manages AWS accounts, I want to know where to go for canonical and tracking information.

## Acceptance criteria

- All sheets/columns in that spreadsheet are actively in use
- All sheets/columns that are no longer active are deleted or marked as deprecated

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
This was completed as of 9/20
