### ISSUE TITLE
Create an AWS role with SecurityAudit policy for cross account access - for dedicated readonly auditing

### ISSUE THREAD

**Issue by JJediny** [18F/aws-admin#72]
To reduce complications and blast radius of using an assume role with admin rights to conduct simple checks and scans. A new role should be created with read only privileges to be used for CI/CD.

## Implementation  
- [x] Create a new group for readonly role
- [x] Attach the standard  AWS `securityaudit` policy to the group
- [x] Create a assumerole user and add them to the readonly group in all accounts
- [x] Test using the new role to connect to all the accounts from the jump account
- [x] Document how/when to use the new role
- [x] Shared the credentials for the new role in circleci

## Acceptance Criteria 
- [x] New readonly role created, documented, and ready for use

**Comment by afeld** [comment]
Still being worked on.
