### ISSUE TITLE
Explore Cognito as a federated login solution

### ISSUE THREAD

**Issue by cantsin** [18F/aws-admin#8]
We can configure an identity pool that will allow both login.gov OIDC and SAML authentication. 

Some notes:

- We would want to prevent [unauthenticated login](https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html) (guest users)
- We can ignore all other authentication providers for now
- We still need some glue code/application logic to integrate

Opening up for discussion/ideas.

**Comment by afeld** [comment]
Sounds reasonable to me! Biggest question for me would be how hard it would be to get it working with an Active Directory sync.

**Comment by cantsin** [comment]
Update: we can only configure user pools and even then, we cannot integrate login.gov OIDC, only SAML, because login.gov OIDC requires a `nonce` parameter that AWS Cognito does not supply (and does not seem possible to fake through Cognito Lambda triggers). That work is over at #9 and documentation is at https://docs.google.com/document/d/1qhulMoqbkpZuT_wasosJQkcBgrnwntLuz2SYJWzcklw/edit?usp=sharing (access may be restricted)

**Comment by afeld** [comment]
Ok, calling this done. Thanks!
