### ISSUE TITLE
Use Terraform to Provision new Govcloud accounts

### ISSUE THREAD

**Issue by JJediny** [18F/aws-admin#83]
## Background information
As the tech portfolio member I want a standardized onboarding/provisioning for new accounts. 

```
# Steps for initial user creation

Command to Create a Group:
aws iam create-group -g <group name> --path /

Command to Add a Policy to the group:
aws iam put-group-policy -g <group name> --policy-name <policy name> --policy-document " { \"Version\": \"2012-10-17\", \"Statement\": [ { \"Effect\": \"Allow\", \"Action\": \"*\", \"Resource\": \"*\" } ] } "

Command to create a new user and add them to the group:
aws iam create-user -u <username> --path /
aws iam add-user-to-group -g <group name> -u <username> --path /

Command to add a password to the user:
aws iam create-login-profile -u <username> -p <password>

Command to Verify that your user was created:
aws iam list-users --path-prefix /

Note:
<group name> - The onboard tool sets the group name to Administrators.
<policy name> - The onboard tool sets the policy name to AdminPolicy.
<username> - The onboard tool sets the username to Administrator.
<password> - A password of your choosing.
```
## Implementation

- [ ] Document the step currently missing from docs 
   - [ ] Once the list of commercial accounts are provided, AWS will provide password protected PDFs and ask you to call them for the password
   - [ ] Once unlocked the account #, secret and access key are provided (save in keepass)
 - [ ] create a terraform module (for the steps above) using exported ENV creds (not terraform state) to perform creating the groups and two users (1 for requestor 1 for tech portfolio).
- [ ] generate random password (save to keepass)
- [ ] setup 2FA (save QR code to keepass as file attachment)

## Acceptance
- [ ] Docs are published and terraform code and steps are repeatable by others

**Comment by afeld** [comment]
Just created https://github.com/18F/aws-admin/issues/84, which is a bit more specific to the account creation part.

**Comment by JJediny** [comment]
https://github.com/18F/aws-admin/blob/master/bin/set_up_govcloud.sh

**Comment by amitfreeman-gov** [comment]
My take here is we do not need terraform to assign passwords or assign MFA devices - these are going to be reset by the user in any event, and therefore wouldn't be retained in state.  The terraformed objects IMO should be created with NO console access, no access keys, and no MFA devices.  While it would require manually generating a password (Set to expire on login), this would anyway need to be either manually entered into keypass (if unique), manually given to the user (again, if unique), or, as far as my creativity restricts me, predictable (which would not be ideal).  

As far as the OTP portion, if access is restricted to require the "MFAAuthneticated = true" condition for anything other than adding the MFA device, the account will be useless unless the user immediately enables their MFA.

**Comment by amitfreeman-gov** [comment]
My vote would be yes.  IAM should be managed and auditable (in git history).  It also permits programatic destruction in a controlled fashion (not implying that you cannot use awscli commands to do that, just that terraform does this for you). 

Additionally, provisioning in terraform may be templated.  The manual step happens either way, however it seems much more sensible to have as much as possible "as-code".

**Comment by amitfreeman-gov** [comment]
It also alleviates having to do what's being done right now via cloudcustodian outputting state, removing from the statefile what we want to destroy, and then rerunning terraform.  If we terraformed out of the gate, terraform state would have the canonical state to begin with.

**Comment by JJediny** [comment]
partially automated (https://github.com/18F/aws-admin/blob/master/bin/set_up_govcloud.sh ) and given the infrequency `not going to do`.
