### ISSUE TITLE
sandbox account for [jhodys661game@gmail.com]

### ISSUE THREAD

**Issue by jhodys** [18F/aws-admin#89]
_By making this request, you are agreeing to [the rules](https://before-you-ship.18f.gov/infrastructure/sandbox/#rules)._

## For admins

1. [x] Sign into the sandbox account, either directly or through [cross-account access](https://github.com/18F/aws-admin#signing-in-to-destination-accounts)
1. [x] [Add a new user](https://console.aws.amazon.com/iam/home#/users$new?step=details)
   - Use their GSA email as their username
   - Enable `AWS Management Console access`
   - Add to group `sandbox-power-user`
1. [x] Send them the temporary password via Google Hangouts
1. [x] Have them confirm they set up MFA

**Comment by afeld** [comment]
Sorry, this is only for TTS staff.
